language: node_js
node_js:
  - '8'
  - '10'
os:
  - linux
  - osx
  - windows
notifications:
  email: false
branches:
  only:
  - master
  - dev
  - /^v\d+\.\d+\.\d+.*$/

jobs:
  include:
    - stage: "Coverall"
      node_js: 10
      os: linux
      branches:
        only:
        - master
      script:
        - npm run test:cov
      after_success: skip
